# config/routes.yaml

# the "app_lucky_number" route name is not important yet
home_controller:
    path: /
    controller: App\Controller\HomeController::index
app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number
app_lucky_string:
    path: /lucky/string
    controller: App\Controller\LuckyController::string
